import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie BD APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} dark:bg-body bg-white font-[Sora] dark:text-white text-dark`}
      >
        <Navbar />
        <div>{children}</div>
        <Footer />
        <div
          id="modal-root-content"
          className="modal-content dark:bg-body dark:text-white"
        ></div>
      </body>
    </html>
  );
}
